apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    trains: fileserver
    platform: trains
  name: fileserver
  namespace: {{ .Values.trains.namespace }}
spec:
  replicas: 1
  minReadySeconds: 15
  progressDeadlineSeconds: 180
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        trains: fileserver
        platform: trains
    spec:
      containers:
      - image: {{ .Values.trains.image.repository }}:{{ .Values.trains.image.tag }}
        name: fileserver
        args:
        - fileserver
        volumeMounts:
        - mountPath: /var/log/trains
          name: storage
          subPath: trains-logs
        - mountPath: /mnt/fileserver
          name: storage
          subPath: trains
      restartPolicy: Always
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
      volumes:
      - flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            clusterNamespace: rook-ceph
            fsName: ml-fs
        name: storage
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}

