apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    trains: mongo
    platform: trains
  name: mongo
  namespace: {{ .Values.trains.namespace }}
spec:
  replicas: 1
  minReadySeconds: 15
  progressDeadlineSeconds: 180
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        trains: mongo
        platform: trains
    spec:
      containers:
      - image: mongo:3.6.5
        name: mongo
        volumeMounts:
        - mountPath: /data/db
          name: mongo-hostpath0
        - mountPath: /data/configdb
          name: mongo-hostpath1
      restartPolicy: Always
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
      volumes:
      - name: mongo-hostpath0
        persistentVolumeClaim:
          claimName: mongo-db
      - name: mongo-hostpath1
        persistentVolumeClaim:
          claimName: mongo-conf
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-db
spec:
  storageClassName: gp2-eu-west-1c
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-conf
spec:
  storageClassName: gp2-eu-west-1c
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
